# Generated by Django 4.0.2 on 2022-02-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('inType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inTypes', to='brewr.intype')),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abv', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prep', models.TextField()),
                ('steep', models.TextField()),
                ('boil', models.TextField()),
                ('cooldown', models.TextField()),
                ('pitch', models.TextField()),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='brewr.ingredient')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='brewr.style')),
            ],
        ),
    ]
