# Generated by Django 4.0.2 on 2022-02-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewr', '0002_remove_beer_ingredients_ingredient_beer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer', to='brewr.beer'),
        ),
    ]
